name: Use Node.js

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: ['24.x', '']
        os: [ubuntu-slim, ubuntu-latest]

    steps:
      - uses: actions/checkout@v6
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: node -v || echo "Node.js not available"
